# Minimal SwiftLint pre-commit configuration for Meshtastic iOS app
# Designed to avoid SourceKit framework issues

# Exclude all problematic directories
excluded:
  - MeshtasticProtobufs
  - .github
  - ci_scripts
  - .git
  - Widgets
  - scripts
  - MeshtasticTests
  - protobufs
  - Settings.bundle

# Only include the main source directory
included:
  - Meshtastic

# Minimal rules that don't require SourceKit
disabled_rules:
  - all
