name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -workspace "Meshtastic.xcworkspace"

      - name: Build dot SAGA (iOS)
        run: |
          set -o pipefail
          xcodebuild \
            -workspace "Meshtastic.xcworkspace" \
            -scheme "dot SAGA" \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            clean build | xcpretty -c || xcodebuild -workspace "Meshtastic.xcworkspace" -scheme "dot SAGA" -destination 'generic/platform=iOS' -configuration Release clean build
